// GENERATED by packaging/generate-types.mjs — do not edit.
// Regenerate with: node packaging/generate-types.mjs

// Option name -> [environment variable, kind]. The kind drives coercion: the
// engine reads strings, so a boolean has to arrive as "true", a glob list as a
// comma-separated string, and a number as its decimal form.
const CONFIG_ENV = {
  agentic: ["AGENTIC", "Bool"],
  bbApiToken: ["BB_API_TOKEN", "Secret"],
  bbEmail: ["BB_EMAIL", "Str"],
  bitbucketWebhookSecret: ["BITBUCKET_WEBHOOK_SECRET", "Secret"],
  blastMaxRefs: ["BLAST_MAX_REFS", "Int"],
  blastMaxSymbols: ["BLAST_MAX_SYMBOLS", "Int"],
  blastRadius: ["BLAST_RADIUS", "Bool"],
  ciStatus: ["CI_STATUS", "Bool"],
  commentMarker: ["COMMENT_MARKER", "Str"],
  complexityMetrics: ["COMPLEXITY_METRICS", "Bool"],
  complexityMinCyclomatic: ["COMPLEXITY_MIN_CYCLOMATIC", "Int"],
  cveMaxPackages: ["CVE_MAX_PACKAGES", "Int"],
  cveScan: ["CVE_SCAN", "Bool"],
  describeInstructions: ["DESCRIBE_INSTRUCTIONS", "Str"],
  diagram: ["DIAGRAM", "Bool"],
  diagramMaxNodes: ["DIAGRAM_MAX_NODES", "Int"],
  excludeGlobs: ["EXCLUDE_GLOBS", "Globs"],
  extraSystemPrompt: ["EXTRA_SYSTEM_PROMPT", "Str"],
  extraSystemPromptFile: ["EXTRA_SYSTEM_PROMPT_FILE", "Path"],
  fileBundling: ["FILE_BUNDLING", "Bool"],
  ghApiBase: ["GH_API_BASE", "Str"],
  ghToken: ["GH_TOKEN", "Secret"],
  githubWebhookSecret: ["GITHUB_WEBHOOK_SECRET", "Secret"],
  gitlabApiBase: ["GITLAB_API_BASE", "Str"],
  gitlabToken: ["GITLAB_TOKEN", "Secret"],
  gitlabWebhookSecret: ["GITLAB_WEBHOOK_SECRET", "Secret"],
  grepContext: ["GREP_CONTEXT", "Bool"],
  includeGlobs: ["INCLUDE_GLOBS", "Globs"],
  llmBaseUrl: ["LLM_BASE_URL", "Str"],
  maxDiffChars: ["MAX_DIFF_CHARS", "Int"],
  maxFindings: ["MAX_FINDINGS", "Int"],
  maxHistoryChars: ["MAX_HISTORY_CHARS", "Int"],
  maxTurns: ["MAX_TURNS", "Int"],
  minConfidence: ["MIN_CONFIDENCE", "Int"],
  openrouterApiKey: ["OPENROUTER_API_KEY", "Secret"],
  openrouterHttpReferer: ["OPENROUTER_HTTP_REFERER", "Str"],
  openrouterMaxRetries: ["OPENROUTER_MAX_RETRIES", "Int"],
  openrouterMaxTokens: ["OPENROUTER_MAX_TOKENS", "Int"],
  openrouterModel: ["OPENROUTER_MODEL", "Str"],
  openrouterModelExplore: ["OPENROUTER_MODEL_EXPLORE", "Str"],
  openrouterTemperature: ["OPENROUTER_TEMPERATURE", "Float"],
  openrouterTimeoutSecs: ["OPENROUTER_TIMEOUT_SECS", "Int"],
  openrouterXTitle: ["OPENROUTER_X_TITLE", "Str"],
  osvApiBase: ["OSV_API_BASE", "Str"],
  port: ["PORT", "Int"],
  prbotRunLog: ["PRBOT_RUN_LOG", "Path"],
  prBody: ["PR_BODY", "Bool"],
  prBodyMaxChars: ["PR_BODY_MAX_CHARS", "Int"],
  reanchorFindings: ["REANCHOR_FINDINGS", "Bool"],
  reviewOnUpdate: ["REVIEW_ON_UPDATE", "Bool"],
  selfCritique: ["SELF_CRITIQUE", "Bool"],
  structuralContext: ["STRUCTURAL_CONTEXT", "Bool"],
  structuralMaxFiles: ["STRUCTURAL_MAX_FILES", "Int"],
  suggestions: ["SUGGESTIONS", "Bool"],
  userAgent: ["USER_AGENT", "Str"],
  vendoredGlobs: ["VENDORED_GLOBS", "Globs"],
  walkthrough: ["WALKTHROUGH", "Bool"],
  walkthroughMaxSymbols: ["WALKTHROUGH_MAX_SYMBOLS", "Int"],
  workerToken: ["WORKER_TOKEN", "Secret"],
};

/** Turn a `config` object into the environment variables the engine reads. */
function configToEnv(config) {
  const env = {};
  for (const [key, value] of Object.entries(config || {})) {
    const entry = CONFIG_ENV[key];
    // Unknown keys are rejected rather than dropped, for the same reason
    // unknown review options are: a silently ignored `dryRun` posts a live
    // review, and a silently ignored `minConfidence` ships every nit.
    if (!entry) throw new TypeError(`kaniscope: unknown config option ${JSON.stringify(key)}`);
    if (value === undefined || value === null) continue;
    const [name, kind] = entry;
    env[name] =
      kind === "Bool" ? (value ? "true" : "false")
      : kind === "Globs" ? (Array.isArray(value) ? value.join(",") : String(value))
      : String(value);
  }
  return env;
}

module.exports = { CONFIG_ENV, configToEnv };
