// GENERATED by packaging/generate-types.mjs — do not edit.
// Regenerate with: node packaging/generate-types.mjs

/** Result of one review run (serialized as the HTTP/CLI response). */
export interface RunReviewOutput {
  commentUrl?: string | null;
  findings: number;
  /** The post-processed findings that were posted (after self-critique, confidence floor, sort, and cap). */
  findingsDetail?: Finding[];
  /** The inline comments exactly as they were built — path, line, and the rendered body, committable suggestion block and all. */
  inlineDetail?: InlineComment[];
  inlinePosted: number;
  model: string;
  posted: boolean;
  pr: number;
  provider: string;
  recommendation: string;
  repo: string;
  summaryMarkdown: string;
  usage?: Usage | null;
}

/** One review finding from the model. */
export interface Finding {
  body: string;
  /** Model's confidence (0–100) that this is a real, actionable issue a senior reviewer would flag. */
  confidence?: number | null;
  file?: string;
  line?: number | null;
  severity?: string;
  /** Replacement text for the anchored line, ready to render as a committable suggestion — or `None` whenever the fix is not expressible as an exact line replacement, which is most of the time. */
  suggestion?: string | null;
}

/** One inline comment anchored to a file + line on the new side of the diff. */
export interface InlineComment {
  body: string;
  line: number;
  path: string;
}

/** Token accounting echoed back by OpenRouter. */
export interface Usage {
  completion_tokens?: number | null;
  prompt_tokens?: number | null;
  total_tokens?: number | null;
}

/** One file review. */
export interface FileReviewOutput {
  commentUrl?: string | null;
  outcome: FileReviewOutcome;
  path: string;
  /** Always false here. */
  posted: boolean;
  source: FileSource;
  /** The result as a comment body — what the PR command posts, and what a CLI caller prints. */
  summaryMarkdown: string;
}

/** The file was read and reviewed. */
export interface FileReviewOutcomeReviewed {
  /** After the confidence floor, severity sort and cap — the same policy a diff review applies, so a finding here means what it means there. */
  findings: Finding[];
  recommendation: string;
  status: "reviewed";
  summary: string;
}

/** The path is excluded by this repository's review file filters. */
export interface FileReviewOutcomeExcluded {
  reason: string;
  status: "excluded";
}

/** No such file at the resolved source. */
export interface FileReviewOutcomeNotFound {
  reason: string;
  status: "notFound";
}

/** What came of the request. */
export type FileReviewOutcome = FileReviewOutcomeReviewed | FileReviewOutcomeExcluded | FileReviewOutcomeNotFound;

/** A checkout on disk. */
export interface FileSourceLocal {
  kind: "local";
  repoRoot: string;
}

/** A host, at a specific ref — named, because "the file" is meaningless without saying which revision of it was read. */
export interface FileSourcePr {
  gitRef: string;
  kind: "pr";
  pr: number;
  provider: string;
  repo: string;
}

/** Where the reviewed file was read from. */
export type FileSource = FileSourceLocal | FileSourcePr;

/** Everything that shapes one review, resolved and redacted. */
export interface EffectiveRules {
  /** The exact text appended to the backend's system prompt — calibration rules, the suggestion rules when enabled, and the consumer's `EXTRA_PROMPT` with any repository `instructions` already merged in. */
  injectedRules: string;
  repoConfig: RepoConfigSource;
  scope: RulesScope;
  settings: ReviewSettings;
  /** Anything that failed open on the way here. */
  warnings: string[];
}

/** Per-repo review overrides parsed from a `.prbot.toml`. */
export interface RepoConfig {
  agentic?: boolean | null;
  /** Cap on the stated change intent handed to the reviewer on a local review, for this repo. */
  change_intent_max_chars?: number | null;
  /** Toggle fetching the head commit's CI results into the prompt for this repo. */
  ci_status?: boolean | null;
  /** Toggle the OSV.dev dependency vulnerability scan for this repo. */
  cve_scan?: boolean | null;
  /** Instructions shaping the `/describe` output specifically — a house PR description layout, release-notes sections, a contributor table. */
  describe_instructions?: string | null;
  exclude_globs?: string[] | null;
  /** Toggle grouping related changed files (source + test, i18n siblings) when packing a large diff, for this repo. */
  file_bundling?: boolean | null;
  /** Let the agentic reviewer's `grep` return context lines around each match, for this repo. */
  grep_context?: boolean | null;
  include_globs?: string[] | null;
  /** Extra review instructions in plain language, appended to the system prompt. */
  instructions?: string | null;
  max_findings?: number | null;
  min_confidence?: number | null;
  model?: string | null;
  model_explore?: string | null;
  /** Pass this repo's PR descriptions to the reviewer as a statement of intent to check the diff against. */
  pr_body?: boolean | null;
  /** Cap on the description handed to the reviewer, for this repo. */
  pr_body_max_chars?: number | null;
  /** Toggle re-anchoring a finding that drifted just off a diff line to the nearest matching diff line (else it folds to the summary), for this repo. */
  reanchor_findings?: boolean | null;
  self_critique?: boolean | null;
  /** Toggle committable suggestion blocks on findings, for this repo. */
  suggestions?: boolean | null;
  /** Globs marking vendored third-party source (`thirdparty/**`, `vendor/**`, …). */
  vendored?: string[] | null;
}

/** Nothing to read against — no checkout, or a PR with no ref to fetch from. */
export interface RepoConfigSourceUnavailable {
  reason: string;
  status: "unavailable";
}

/** Looked, and the repository ships no `.prbot.toml`. */
export interface RepoConfigSourceAbsent {
  location: string;
  status: "absent";
}

/** Read, parsed, and merged over the environment config. */
export interface RepoConfigSourceApplied {
  location: string;
  /** Exactly the keys the file set. */
  overrides: RepoConfig;
  status: "applied";
}

/** Read, but rejected — invalid TOML or an unknown key. */
export interface RepoConfigSourceInvalid {
  error: string;
  location: string;
  status: "invalid";
}

/** Where the per-repo configuration came from, and what it said. */
export type RepoConfigSource = RepoConfigSourceUnavailable | RepoConfigSourceAbsent | RepoConfigSourceApplied | RepoConfigSourceInvalid;

/** The review-relevant configuration, after merging repo overrides. */
export interface ReviewSettings {
  agentic: boolean;
  blastMaxRefs: number;
  blastMaxSymbols: number;
  blastRadius: boolean;
  changeIntentMaxChars: number;
  ciStatus: boolean;
  /** The signature appended to every comment this deployment posts. */
  commentMarker: string;
  complexityMetrics: boolean;
  complexityMinCyclomatic: number;
  cveMaxPackages: number;
  cveScan: boolean;
  diagram: boolean;
  diagramMaxNodes: number;
  excludeGlobs: string[];
  fileBundling: boolean;
  grepContext: boolean;
  includeGlobs: string[];
  maxDiffChars: number;
  maxFindings: number;
  maxHistoryChars: number;
  maxTokens: number;
  maxTurns: number;
  minConfidence: number;
  model: string;
  modelExplore: string;
  prBody: boolean;
  prBodyMaxChars: number;
  reanchorFindings: boolean;
  reviewSamples: number;
  sampleLineTolerance: number;
  sampleMinAgreement: number;
  selfCritique: boolean;
  structuralContext: boolean;
  structuralMaxFiles: number;
  suggestions: boolean;
  temperature: number;
  vendoredGlobs: string[];
  walkthrough: boolean;
  walkthroughMaxSymbols: number;
}

/** A checkout on disk — the pre-PR path. */
export interface RulesScopeLocal {
  kind: "local";
  /** The directory whose `.prbot.toml` was consulted. */
  repoRoot: string;
}

/** A pull request on a host. */
export interface RulesScopePr {
  kind: "pr";
  pr: number;
  provider: string;
  repo: string;
}

/** What the rules were resolved for. */
export type RulesScope = RulesScopeLocal | RulesScopePr;

/** The findings currently on one pull request. */
export interface FindingsOutput {
  /** The PR's head as of this call, when the provider reported one. */
  headSha?: string | null;
  outcome: FindingsOutcome;
  pr: number;
  provider: string;
  repo: string;
  /** Present when at least one active finding was written against a commit other than the current head. */
  revisionWarning?: string | null;
}

/** Where a finding is in its lifecycle. */
export type FindingState = "active" | "resolved" | "unparseable";

/** The provider tracks finding lifecycle and this is what it holds. */
export interface FindingsOutcomeListed {
  /** Open findings — the ones worth acting on. */
  active: OutstandingFinding[];
  /** Findings the provider considers closed. */
  resolved: OutstandingFinding[];
  status: "listed";
  /** Bot comments that carry no fingerprint and cannot be matched. */
  unparseable: OutstandingFinding[];
}

/** This provider cannot answer the question, and why. */
export interface FindingsOutcomeUnsupported {
  reason: string;
  status: "unsupported";
}

/** Whether the provider could answer at all. */
export type FindingsOutcome = FindingsOutcomeListed | FindingsOutcomeUnsupported;

/** One finding as it currently exists on the pull request. */
export interface OutstandingFinding {
  /** The comment body as posted, rendered markdown and all. */
  body: string;
  /** The provider's id for the comment, for a caller that wants to link to it. */
  commentId: string;
  /** The reconciliation fingerprint — stable across rewordings of the same finding, and the identity to pass back to `resolve-findings`. */
  fingerprint?: string | null;
  /** The line the provider currently tracks this thread at — which is not necessarily the line it was posted on, since a provider moves a thread as the file is edited beneath it. */
  line?: number | null;
  /** The commit this finding was first written against. */
  originalCommit?: string | null;
  path: string;
  state: FindingState;
  /** The provider's thread id, where it has threads. */
  threadId?: string | null;
}

/** A bundle of findings handed over for investigation. */
export interface ResolveOutput {
  /** Stated in the payload, not left to the caller's memory. */
  disclaimer: string;
  handoffs: FindingHandoff[];
  headSha?: string | null;
  pr: number;
  provider: string;
  repo: string;
  /** Set when the provider cannot track findings at all, with the reason. */
  unsupported?: string | null;
}

/** One finding, packaged for a coding agent to act on. */
export interface FindingHandoff {
  action: HandoffAction;
  /** Absent only for [`HandoffAction::NotFound`]. */
  finding?: OutstandingFinding | null;
  /** Why this action, in one sentence a caller can show a user. */
  rationale: string;
  /** The identity that was asked for — echoed back so a caller can match up a request that produced [`HandoffAction::NotFound`]. */
  requested: string;
}

/** What a caller should do with one selected finding. */
export type HandoffAction = "investigate" | "reverifyAgainstHead" | "alreadyResolved" | "notFound" | "needsHumanJudgement";

/** One finding explained against a local checkout. */
export interface ExplainOutput {
  explanation: Explanation;
  /** The finding as given. */
  finding: ExplainInput;
  /** Set when the finding names a revision that is not the one that was read. */
  revisionWarning?: string | null;
}

/** The finding to explain. */
export interface ExplainInput {
  /** What the reviewer said. */
  body: string;
  file: string;
  line?: number | null;
  /** The commit the finding was written against, when known. */
  originalCommit?: string | null;
  severity?: string | null;
}

/** A structured explanation of one finding, checked against real code. */
export interface Explanation {
  /** What goes wrong if the claim holds, in terms of behaviour rather than style. */
  affectedBehavior: string;
  /** What the finding asserts, restated plainly. */
  claim: string;
  /** What in the code supports or contradicts it — file, line, and what is actually there. */
  evidence: string;
  /** How a person could confirm or refute this — a test to write, a command to run, a line to read. */
  suggestedVerification: string;
  /** What the explanation could not settle. */
  uncertainty: string;
  /** Whether the investigation found the finding to hold. */
  verdict: ExplanationVerdict;
}

/** What the investigation concluded. */
export type ExplanationVerdict = "holds" | "doesNotHold" | "inconclusive";

