// GENERATED by packaging/generate-types.mjs — do not edit.
// Regenerate with: node packaging/generate-types.mjs

/** Result of one review run (serialized as the HTTP/CLI response). */
export interface RunReviewOutput {
  commentUrl?: string | null;
  findings: number;
  /** The post-processed findings that were posted (after self-critique, confidence floor, sort, and cap). */
  findingsDetail?: Finding[];
  /** The inline comments exactly as they were built — path, line, and the rendered body, committable suggestion block and all. */
  inlineDetail?: InlineComment[];
  inlinePosted: number;
  model: string;
  posted: boolean;
  pr: number;
  provider: string;
  recommendation: string;
  repo: string;
  summaryMarkdown: string;
  usage?: Usage | null;
}

/** One review finding from the model. */
export interface Finding {
  body: string;
  /** Model's confidence (0–100) that this is a real, actionable issue a senior reviewer would flag. */
  confidence?: number | null;
  file?: string;
  line?: number | null;
  severity?: string;
  /** Replacement text for the anchored line, ready to render as a committable suggestion — or `None` whenever the fix is not expressible as an exact line replacement, which is most of the time. */
  suggestion?: string | null;
}

/** One inline comment anchored to a file + line on the new side of the diff. */
export interface InlineComment {
  body: string;
  line: number;
  path: string;
}

/** Token accounting echoed back by OpenRouter. */
export interface Usage {
  completion_tokens?: number | null;
  prompt_tokens?: number | null;
  total_tokens?: number | null;
}

