# GENERATED by packaging/generate-types.mjs — do not edit.
# Regenerate with: node packaging/generate-types.mjs

from __future__ import annotations

from typing import Any, Dict, List, Mapping, Optional, TypedDict


class ReviewConfig(TypedDict, total=False):
    """Typed overrides for the engine's environment-driven configuration.

    Every field maps to one environment variable. Passing `config` is exactly
    equivalent to setting those variables, and `env` still wins over it.
    """

    # Clone the repo and let the model investigate cross-file context (grep / read_file / list_dir) before writing findings. Default: `false`. (`AGENTIC`)
    agentic: bool
    # Atlassian API token for Bitbucket. (`BB_API_TOKEN`)
    bb_api_token: str
    # Atlassian account email, paired with BB_API_TOKEN for Bitbucket basic auth. (`BB_EMAIL`)
    bb_email: str
    # HMAC secret for Bitbucket webhook deliveries. (`BITBUCKET_WEBHOOK_SECRET`)
    bitbucket_webhook_secret: str
    # References reported per symbol by the blast-radius scan. Default: `8`. (`BLAST_MAX_REFS`)
    blast_max_refs: int
    # Changed symbols the blast-radius scan will follow. Default: `12`. (`BLAST_MAX_SYMBOLS`)
    blast_max_symbols: int
    # Precompute callers, tests and type uses of changed symbols and seed the agentic reviewer with them. Measured no recall gain on well-named repos; may help on large monorepos. Default: `true`. (`BLAST_RADIUS`)
    blast_radius: bool
    # Fetch the head commit's CI results so the reviewer cannot assert a broken build CI already decided. One extra API call per review. Default: `true`. (`CI_STATUS`)
    ci_status: bool
    # Signature appended to every comment, and the dedupe key for finding the bot's own comments on re-review. Default: `🤖 ai-pr-review`. (`COMMENT_MARKER`)
    comment_marker: str
    # Report cyclomatic and cognitive complexity (A-F) for touched functions. Deterministic; no model call. Default: `true`. (`COMPLEXITY_METRICS`)
    complexity_metrics: bool
    # Only surface functions at or above this cyclomatic complexity. Default: `8`. (`COMPLEXITY_MIN_CYCLOMATIC`)
    complexity_min_cyclomatic: int
    # Distinct packages queried against OSV per review. Default: `100`. (`CVE_MAX_PACKAGES`)
    cve_max_packages: int
    # Check added lockfile entries against OSV.dev for known vulnerabilities. Default: `true`. (`CVE_SCAN`)
    cve_scan: bool
    # Free-form instructions shaping /describe output. Outranks the built-in layout. (`DESCRIBE_INSTRUCTIONS`)
    describe_instructions: str
    # Append the mermaid change diagram. Skipped on Bitbucket, and whenever there are no edges to draw. Default: `false`. (`DIAGRAM`)
    diagram: bool
    # Symbols considered for edge linking, and so the diagram's node budget. Default: `12`. (`DIAGRAM_MAX_NODES`)
    diagram_max_nodes: int
    # Globs skipped before the model call. Setting this REPLACES the lockfile/generated/vendored/minified defaults. (`EXCLUDE_GLOBS`)
    exclude_globs: List[str]
    # Appended to the built-in system prompts. Your conventions, in plain language. Set but empty is the same as unset: EXTRA_SYSTEM_PROMPT_FILE is consulted either way. (`EXTRA_SYSTEM_PROMPT`)
    extra_system_prompt: str
    # Path whose contents are used when EXTRA_SYSTEM_PROMPT is unset OR empty. For baking a large conventions block into an image. (`EXTRA_SYSTEM_PROMPT_FILE`)
    extra_system_prompt_file: str
    # Keep related files (a source and its test, i18n siblings) adjacent when packing, so the model reviews them together. Default: `true`. (`FILE_BUNDLING`)
    file_bundling: bool
    # GitHub API base. Point at a GitHub Enterprise host. Default: `https://api.github.com`. (`GH_API_BASE`)
    gh_api_base: str
    # GitHub token used to read the PR and post comments. (`GH_TOKEN`)
    gh_token: str
    # HMAC secret GitHub signs webhook deliveries with. (`GITHUB_WEBHOOK_SECRET`)
    github_webhook_secret: str
    # GitLab API base. Point at a self-hosted instance. Default: `https://gitlab.com/api/v4`. (`GITLAB_API_BASE`)
    gitlab_api_base: str
    # GitLab token used to read the MR and post notes. (`GITLAB_TOKEN`)
    gitlab_token: str
    # Token GitLab sends as X-Gitlab-Token on webhook deliveries. (`GITLAB_WEBHOOK_SECRET`)
    gitlab_webhook_secret: str
    # Let the agentic reviewer's grep request 1-8 lines of context per match, so it can judge a second site without a read_file round trip. Default: `true`. (`GREP_CONTEXT`)
    grep_context: bool
    # If set, ONLY files matching these globs are reviewed. (`INCLUDE_GLOBS`)
    include_globs: List[str]
    # OpenAI-compatible endpoint, e.g. http://localhost:11434/v1 for Ollama. Default: `https://openrouter.ai/api/v1`. (`LLM_BASE_URL`)
    llm_base_url: str
    # Size budget for the packed diff. Beyond it, whole files are ranked and dropped rather than truncated mid-hunk. Default: `200000`. (`MAX_DIFF_CHARS`)
    max_diff_chars: int
    # Cap findings per PR, ranked by severity then confidence. Default: `20`. (`MAX_FINDINGS`)
    max_findings: int
    # Cap on the agentic conversation carried between turns. Default: `45000`. (`MAX_HISTORY_CHARS`)
    max_history_chars: int
    # Tool-call turns the agentic reviewer may take before it must conclude. Default: `6`. (`MAX_TURNS`)
    max_turns: int
    # Drop findings below this confidence (0-100). Default: `0`. (`MIN_CONFIDENCE`)
    min_confidence: int
    # API key for the OpenAI-compatible endpoint. Required for every review. (`OPENROUTER_API_KEY`)
    openrouter_api_key: str
    # HTTP-Referer sent to OpenRouter, for its dashboard attribution. Default: `https://github.com/nhatvu148/pr-review-core`. (`OPENROUTER_HTTP_REFERER`)
    openrouter_http_referer: str
    # Retries on a failed or rate-limited model call. Default: `3`. (`OPENROUTER_MAX_RETRIES`)
    openrouter_max_retries: int
    # Cap on completion tokens per model call. Default: `4000`. (`OPENROUTER_MAX_TOKENS`)
    openrouter_max_tokens: int
    # Model that writes the review, and the synthesis half of the agentic split. Default: `anthropic/claude-sonnet-4.5`. (`OPENROUTER_MODEL`)
    openrouter_model: str
    # Cheaper model for the agentic explore turns, before synthesis. Default: `moonshotai/kimi-k2-0905`. (`OPENROUTER_MODEL_EXPLORE`)
    openrouter_model_explore: str
    # Sampling temperature. Low on purpose: a review should be reproducible. Default: `0.2`. (`OPENROUTER_TEMPERATURE`)
    openrouter_temperature: float
    # Per-request timeout for a model call. Default: `120`. (`OPENROUTER_TIMEOUT_SECS`)
    openrouter_timeout_secs: int
    # X-Title sent to OpenRouter, for its dashboard attribution. Default: `pr-review`. (`OPENROUTER_X_TITLE`)
    openrouter_x_title: str
    # OSV API base. Override for a mirror or a test double. Default: `https://api.osv.dev`. (`OSV_API_BASE`)
    osv_api_base: str
    # HTTP port for a bot serving webhooks. 8088 locally to dodge the usual Docker Desktop clash on 8080. Default: `8088`. (`PORT`)
    port: int
    # Path to append one JSON record per review to. `-` means stdout; empty means off, so a line in an env file can disable it without being deleted. (`PRBOT_RUN_LOG`)
    prbot_run_log: str
    # Give the reviewer the PR's own description as a statement of intent to check the diff against. Rendered inside an untrusted fence, so it can never direct the review. Default: `true`. (`PR_BODY`)
    pr_body: bool
    # Cap on the description handed to the reviewer. A clipped one is marked truncated, so absence is not read as out-of-scope. Default: `12000`. (`PR_BODY_MAX_CHARS`)
    pr_body_max_chars: int
    # Snap a finding that drifted just off a diff line onto the nearest diff line sharing its code symbol, instead of folding it into the summary. Default: `true`. (`REANCHOR_FINDINGS`)
    reanchor_findings: bool
    # Re-review automatically when a PR gets new commits. Off by default: pushing is the inner loop, and every round costs a full review. Default: `false`. (`REVIEW_ON_UPDATE`)
    review_on_update: bool
    # Ask the backend for N independent reviews and union the findings. One review pass is a sample, not a sweep: on a frozen commit consecutive reviews shared only 61-74% of their findings. Costs N times the tokens and wall clock; buys recall. Default: `1`. (`REVIEW_SAMPLES`)
    review_samples: int
    # How far apart two samples may anchor the same issue and still merge. Set from measurement: the same issue was observed 1, 7, 10, 12 and 39 lines from where another run reported it. The reconciler uses the same window for the same reason, since both answer whether two descriptions are one issue. Default: `10`. (`SAMPLE_LINE_TOLERANCE`)
    sample_line_tolerance: int
    # How many samples must report a finding for it to survive the merge. One (plain union) by default, because recall is the measured problem; raising it buys precision with the discoveries only one sample made. Default: `1`. (`SAMPLE_MIN_AGREEMENT`)
    sample_min_agreement: int
    # Second skeptical pass that removes false positives and low-value nits. Default: `true`. (`SELF_CRITIQUE`)
    self_critique: bool
    # Name the enclosing function or symbol of each changed line, via tree-sitter, with no clone. Default: `true`. (`STRUCTURAL_CONTEXT`)
    structural_context: bool
    # Files fetched for structural context before it stops. Default: `15`. (`STRUCTURAL_MAX_FILES`)
    structural_max_files: int
    # Attach a committable suggestion block when the model proposed replacement text that validates against the anchored line. Never on a re-anchored finding. Default: `true`. (`SUGGESTIONS`)
    suggestions: bool
    # User-Agent sent to provider APIs. Default: `pr-review-core`. (`USER_AGENT`)
    user_agent: str
    # Globs marking third-party source: hygiene findings are suppressed inside them and the reviewer is told not to edit there. Setting this REPLACES the defaults. (`VENDORED_GLOBS`)
    vendored_globs: List[str]
    # Append the per-file walkthrough table to the summary comment. Default: `false`. (`WALKTHROUGH`)
    walkthrough: bool
    # Symbols listed per file before the cell collapses to (+N more). Default: `4`. (`WALKTHROUGH_MAX_SYMBOLS`)
    walkthrough_max_symbols: int
    # Shared secret authenticating a bot's own async worker callback. (`WORKER_TOKEN`)
    worker_token: str


# Option name -> (environment variable, kind). The kind drives coercion: the
# engine reads strings, so a bool arrives as "true", a glob list as a
# comma-separated string, and a number as its decimal form.
CONFIG_ENV: Dict[str, tuple] = {
    "agentic": ("AGENTIC", "Bool"),
    "bb_api_token": ("BB_API_TOKEN", "Secret"),
    "bb_email": ("BB_EMAIL", "Str"),
    "bitbucket_webhook_secret": ("BITBUCKET_WEBHOOK_SECRET", "Secret"),
    "blast_max_refs": ("BLAST_MAX_REFS", "Int"),
    "blast_max_symbols": ("BLAST_MAX_SYMBOLS", "Int"),
    "blast_radius": ("BLAST_RADIUS", "Bool"),
    "ci_status": ("CI_STATUS", "Bool"),
    "comment_marker": ("COMMENT_MARKER", "Str"),
    "complexity_metrics": ("COMPLEXITY_METRICS", "Bool"),
    "complexity_min_cyclomatic": ("COMPLEXITY_MIN_CYCLOMATIC", "Int"),
    "cve_max_packages": ("CVE_MAX_PACKAGES", "Int"),
    "cve_scan": ("CVE_SCAN", "Bool"),
    "describe_instructions": ("DESCRIBE_INSTRUCTIONS", "Str"),
    "diagram": ("DIAGRAM", "Bool"),
    "diagram_max_nodes": ("DIAGRAM_MAX_NODES", "Int"),
    "exclude_globs": ("EXCLUDE_GLOBS", "Globs"),
    "extra_system_prompt": ("EXTRA_SYSTEM_PROMPT", "Str"),
    "extra_system_prompt_file": ("EXTRA_SYSTEM_PROMPT_FILE", "Path"),
    "file_bundling": ("FILE_BUNDLING", "Bool"),
    "gh_api_base": ("GH_API_BASE", "Str"),
    "gh_token": ("GH_TOKEN", "Secret"),
    "github_webhook_secret": ("GITHUB_WEBHOOK_SECRET", "Secret"),
    "gitlab_api_base": ("GITLAB_API_BASE", "Str"),
    "gitlab_token": ("GITLAB_TOKEN", "Secret"),
    "gitlab_webhook_secret": ("GITLAB_WEBHOOK_SECRET", "Secret"),
    "grep_context": ("GREP_CONTEXT", "Bool"),
    "include_globs": ("INCLUDE_GLOBS", "Globs"),
    "llm_base_url": ("LLM_BASE_URL", "Str"),
    "max_diff_chars": ("MAX_DIFF_CHARS", "Int"),
    "max_findings": ("MAX_FINDINGS", "Int"),
    "max_history_chars": ("MAX_HISTORY_CHARS", "Int"),
    "max_turns": ("MAX_TURNS", "Int"),
    "min_confidence": ("MIN_CONFIDENCE", "Int"),
    "openrouter_api_key": ("OPENROUTER_API_KEY", "Secret"),
    "openrouter_http_referer": ("OPENROUTER_HTTP_REFERER", "Str"),
    "openrouter_max_retries": ("OPENROUTER_MAX_RETRIES", "Int"),
    "openrouter_max_tokens": ("OPENROUTER_MAX_TOKENS", "Int"),
    "openrouter_model": ("OPENROUTER_MODEL", "Str"),
    "openrouter_model_explore": ("OPENROUTER_MODEL_EXPLORE", "Str"),
    "openrouter_temperature": ("OPENROUTER_TEMPERATURE", "Float"),
    "openrouter_timeout_secs": ("OPENROUTER_TIMEOUT_SECS", "Int"),
    "openrouter_x_title": ("OPENROUTER_X_TITLE", "Str"),
    "osv_api_base": ("OSV_API_BASE", "Str"),
    "port": ("PORT", "Int"),
    "prbot_run_log": ("PRBOT_RUN_LOG", "Path"),
    "pr_body": ("PR_BODY", "Bool"),
    "pr_body_max_chars": ("PR_BODY_MAX_CHARS", "Int"),
    "reanchor_findings": ("REANCHOR_FINDINGS", "Bool"),
    "review_on_update": ("REVIEW_ON_UPDATE", "Bool"),
    "review_samples": ("REVIEW_SAMPLES", "Int"),
    "sample_line_tolerance": ("SAMPLE_LINE_TOLERANCE", "Int"),
    "sample_min_agreement": ("SAMPLE_MIN_AGREEMENT", "Int"),
    "self_critique": ("SELF_CRITIQUE", "Bool"),
    "structural_context": ("STRUCTURAL_CONTEXT", "Bool"),
    "structural_max_files": ("STRUCTURAL_MAX_FILES", "Int"),
    "suggestions": ("SUGGESTIONS", "Bool"),
    "user_agent": ("USER_AGENT", "Str"),
    "vendored_globs": ("VENDORED_GLOBS", "Globs"),
    "walkthrough": ("WALKTHROUGH", "Bool"),
    "walkthrough_max_symbols": ("WALKTHROUGH_MAX_SYMBOLS", "Int"),
    "worker_token": ("WORKER_TOKEN", "Secret"),
}


def config_to_env(config: Optional[Mapping[str, Any]]) -> Dict[str, str]:
    """Turn a `config` mapping into the environment variables the engine reads."""
    env: Dict[str, str] = {}
    for key, value in (config or {}).items():
        entry = CONFIG_ENV.get(key)
        # Unknown keys raise rather than being dropped, for the same reason an
        # unknown review kwarg does: a silently ignored dry_run posts a live
        # review, and a silently ignored min_confidence ships every nit.
        if entry is None:
            raise TypeError(f"kaniscope: unknown config option {key!r}")
        if value is None:
            continue
        name, kind = entry
        if kind == "Bool":
            env[name] = "true" if value else "false"
        elif kind == "Globs":
            env[name] = ",".join(value) if isinstance(value, (list, tuple)) else str(value)
        else:
            env[name] = str(value)
    return env
