# GENERATED by packaging/generate-types.mjs — do not edit.
# Regenerate with: node packaging/generate-types.mjs

from __future__ import annotations

from typing import List, Literal, Optional, TypedDict, Union

class _RunReviewOutputRequired(TypedDict):
    findings: int
    inlinePosted: int
    model: str
    posted: bool
    pr: int
    provider: str
    recommendation: str
    repo: str
    summaryMarkdown: str


class RunReviewOutput(_RunReviewOutputRequired, total=False):
    """Result of one review run (serialized as the HTTP/CLI response)."""

    commentUrl: Optional[str]
    findingsDetail: List[Finding]
    inlineDetail: List[InlineComment]
    usage: Optional[Usage]


class _FindingRequired(TypedDict):
    body: str


class Finding(_FindingRequired, total=False):
    """One review finding from the model."""

    confidence: Optional[int]
    file: str
    line: Optional[int]
    severity: str
    suggestion: Optional[str]


class InlineComment(TypedDict):
    """One inline comment anchored to a file + line on the new side of the diff."""

    body: str
    line: int
    path: str


class _UsageRequired(TypedDict):
    pass


class Usage(_UsageRequired, total=False):
    """Token accounting echoed back by OpenRouter."""

    completion_tokens: Optional[int]
    prompt_tokens: Optional[int]
    total_tokens: Optional[int]


class _FileReviewOutputRequired(TypedDict):
    outcome: FileReviewOutcome
    path: str
    posted: bool
    source: FileSource
    summaryMarkdown: str


class FileReviewOutput(_FileReviewOutputRequired, total=False):
    """One file review."""

    commentUrl: Optional[str]


class FileReviewOutcomeReviewed(TypedDict):
    """The file was read and reviewed."""

    findings: List[Finding]
    recommendation: str
    status: Literal["reviewed"]
    summary: str


class FileReviewOutcomeExcluded(TypedDict):
    """The path is excluded by this repository's review file filters."""

    reason: str
    status: Literal["excluded"]


class FileReviewOutcomeNotFound(TypedDict):
    """No such file at the resolved source."""

    reason: str
    status: Literal["notFound"]


# What came of the request.
FileReviewOutcome = Union[FileReviewOutcomeReviewed, FileReviewOutcomeExcluded, FileReviewOutcomeNotFound]


class FileSourceLocal(TypedDict):
    """A checkout on disk."""

    kind: Literal["local"]
    repoRoot: str


class FileSourcePr(TypedDict):
    """A host, at a specific ref — named, because "the file" is meaningless without saying which revision of it was read."""

    gitRef: str
    kind: Literal["pr"]
    pr: int
    provider: str
    repo: str


# Where the reviewed file was read from.
FileSource = Union[FileSourceLocal, FileSourcePr]


class EffectiveRules(TypedDict):
    """Everything that shapes one review, resolved and redacted."""

    injectedRules: str
    repoConfig: RepoConfigSource
    scope: RulesScope
    settings: ReviewSettings
    warnings: List[str]


class _RepoConfigRequired(TypedDict):
    pass


class RepoConfig(_RepoConfigRequired, total=False):
    """Per-repo review overrides parsed from a `.prbot.toml`."""

    agentic: Optional[bool]
    change_intent_max_chars: Optional[int]
    ci_status: Optional[bool]
    cve_scan: Optional[bool]
    describe_instructions: Optional[str]
    exclude_globs: Optional[List[str]]
    file_bundling: Optional[bool]
    grep_context: Optional[bool]
    include_globs: Optional[List[str]]
    instructions: Optional[str]
    max_findings: Optional[int]
    min_confidence: Optional[int]
    model: Optional[str]
    model_explore: Optional[str]
    pr_body: Optional[bool]
    pr_body_max_chars: Optional[int]
    reanchor_findings: Optional[bool]
    self_critique: Optional[bool]
    suggestions: Optional[bool]
    vendored: Optional[List[str]]


class RepoConfigSourceUnavailable(TypedDict):
    """Nothing to read against — no checkout, or a PR with no ref to fetch from."""

    reason: str
    status: Literal["unavailable"]


class RepoConfigSourceAbsent(TypedDict):
    """Looked, and the repository ships no `.prbot.toml`."""

    location: str
    status: Literal["absent"]


class RepoConfigSourceApplied(TypedDict):
    """Read, parsed, and merged over the environment config."""

    location: str
    overrides: RepoConfig
    status: Literal["applied"]


class RepoConfigSourceInvalid(TypedDict):
    """Read, but rejected — invalid TOML or an unknown key."""

    error: str
    location: str
    status: Literal["invalid"]


# Where the per-repo configuration came from, and what it said.
RepoConfigSource = Union[RepoConfigSourceUnavailable, RepoConfigSourceAbsent, RepoConfigSourceApplied, RepoConfigSourceInvalid]


class ReviewSettings(TypedDict):
    """The review-relevant configuration, after merging repo overrides."""

    agentic: bool
    blastMaxRefs: int
    blastMaxSymbols: int
    blastRadius: bool
    changeIntentMaxChars: int
    ciStatus: bool
    commentMarker: str
    complexityMetrics: bool
    complexityMinCyclomatic: int
    cveMaxPackages: int
    cveScan: bool
    diagram: bool
    diagramMaxNodes: int
    excludeGlobs: List[str]
    fileBundling: bool
    grepContext: bool
    includeGlobs: List[str]
    maxDiffChars: int
    maxFindings: int
    maxHistoryChars: int
    maxTokens: int
    maxTurns: int
    minConfidence: int
    model: str
    modelExplore: str
    prBody: bool
    prBodyMaxChars: int
    reanchorFindings: bool
    reviewSamples: int
    sampleLineTolerance: int
    sampleMinAgreement: int
    selfCritique: bool
    structuralContext: bool
    structuralMaxFiles: int
    suggestions: bool
    temperature: float
    vendoredGlobs: List[str]
    walkthrough: bool
    walkthroughMaxSymbols: int


class RulesScopeLocal(TypedDict):
    """A checkout on disk — the pre-PR path."""

    kind: Literal["local"]
    repoRoot: str


class RulesScopePr(TypedDict):
    """A pull request on a host."""

    kind: Literal["pr"]
    pr: int
    provider: str
    repo: str


# What the rules were resolved for.
RulesScope = Union[RulesScopeLocal, RulesScopePr]
