# GENERATED by packaging/generate-types.mjs — do not edit.
# Regenerate with: node packaging/generate-types.mjs

from __future__ import annotations

from typing import List, Optional, TypedDict

class _RunReviewOutputRequired(TypedDict):
    findings: int
    inlinePosted: int
    model: str
    posted: bool
    pr: int
    provider: str
    recommendation: str
    repo: str
    summaryMarkdown: str


class RunReviewOutput(_RunReviewOutputRequired, total=False):
    """Result of one review run (serialized as the HTTP/CLI response)."""

    commentUrl: Optional[str]
    findingsDetail: List[Finding]
    inlineDetail: List[InlineComment]
    usage: Optional[Usage]


class _FindingRequired(TypedDict):
    body: str


class Finding(_FindingRequired, total=False):
    """One review finding from the model."""

    confidence: Optional[int]
    file: str
    line: Optional[int]
    severity: str
    suggestion: Optional[str]


class InlineComment(TypedDict):
    """One inline comment anchored to a file + line on the new side of the diff."""

    body: str
    line: int
    path: str


class _UsageRequired(TypedDict):
    pass


class Usage(_UsageRequired, total=False):
    """Token accounting echoed back by OpenRouter."""

    completion_tokens: Optional[int]
    prompt_tokens: Optional[int]
    total_tokens: Optional[int]
